package com.fbee.modules.mybatis.dao;

import com.fbee.modules.core.persistence.annotation.MyBatisDao;
import com.fbee.modules.mybatis.model.Bank;
import com.fbee.modules.mybatis.model.BankExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
@MyBatisDao
public interface BankMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank
	 * @mbggenerated  Tue May 02 11:55:10 CST 2017
	 */
	int countByExample(BankExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank
	 * @mbggenerated  Tue May 02 11:55:10 CST 2017
	 */
	int deleteByExample(BankExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank
	 * @mbggenerated  Tue May 02 11:55:10 CST 2017
	 */
	int insert(Bank record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank
	 * @mbggenerated  Tue May 02 11:55:10 CST 2017
	 */
	int insertSelective(Bank record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank
	 * @mbggenerated  Tue May 02 11:55:10 CST 2017
	 */
	List<Bank> selectByExample(BankExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank
	 * @mbggenerated  Tue May 02 11:55:10 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Bank record, @Param("example") BankExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bank
	 * @mbggenerated  Tue May 02 11:55:10 CST 2017
	 */
	int updateByExample(@Param("record") Bank record, @Param("example") BankExample example);

	//获取银行列表
    List<Map<Object, String>> selectBankCode();

}