package com.fbee.modules.mybatis.dao;

import com.fbee.modules.core.persistence.annotation.MyBatisDao;
import com.fbee.modules.mybatis.entity.CertsInfoEntity;
import com.fbee.modules.mybatis.model.CertsInfo;
import com.fbee.modules.mybatis.model.CertsInfoExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import com.fbee.modules.mybatis.model.CertsInfoKey;

/**
 *@Description: 
 *
 *@author: zhangsq
 *@date:   2017年3月27日 下午4:48:18
 * 
 */
@MyBatisDao
public interface CertsInfoMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table certs_info
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	int countByExample(CertsInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table certs_info
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	int deleteByExample(CertsInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table certs_info
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	int deleteByPrimaryKey(CertsInfoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table certs_info
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	int insert(CertsInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table certs_info
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	int insertSelective(CertsInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table certs_info
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	List<CertsInfo> selectByExample(CertsInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table certs_info
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	CertsInfo selectByPrimaryKey(CertsInfoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table certs_info
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	int updateByExampleSelective(@Param("record") CertsInfo record, @Param("example") CertsInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table certs_info
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	int updateByExample(@Param("record") CertsInfo record, @Param("example") CertsInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table certs_info
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	int updateByPrimaryKeySelective(CertsInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table certs_info
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	int updateByPrimaryKey(CertsInfo record);

	
	
	
	List<CertsInfoEntity>  checkCertById(CertsInfoEntity certsInfoEntity);
    
  
    List<CertsInfo>  selectCertInfo(CertsInfo certsInfo);
    
    
    
}