package com.fbee.modules.mybatis.dao;

import com.fbee.modules.mybatis.model.OrderChangeStaffInfo;
import com.fbee.modules.mybatis.model.OrderChangeStaffInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderChangeStaffInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_change_staff_info
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    int countByExample(OrderChangeStaffInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_change_staff_info
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    int deleteByExample(OrderChangeStaffInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_change_staff_info
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_change_staff_info
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    int insert(OrderChangeStaffInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_change_staff_info
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    int insertSelective(OrderChangeStaffInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_change_staff_info
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    List<OrderChangeStaffInfo> selectByExample(OrderChangeStaffInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_change_staff_info
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    OrderChangeStaffInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_change_staff_info
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    int updateByExampleSelective(@Param("record") OrderChangeStaffInfo record, @Param("example") OrderChangeStaffInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_change_staff_info
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    int updateByExample(@Param("record") OrderChangeStaffInfo record, @Param("example") OrderChangeStaffInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_change_staff_info
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    int updateByPrimaryKeySelective(OrderChangeStaffInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_change_staff_info
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    int updateByPrimaryKey(OrderChangeStaffInfo record);
}