package com.fbee.modules.mybatis.dao;

import com.fbee.modules.core.persistence.annotation.MyBatisDao;
import com.fbee.modules.mybatis.entity.TenantsCustomersBaseEntity;
import com.fbee.modules.mybatis.model.TenantsCustomersBase;
import com.fbee.modules.mybatis.model.TenantsCustomersBaseExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
@MyBatisDao
public interface TenantsCustomersBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_customers_base
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    int countByExample(TenantsCustomersBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_customers_base
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    int deleteByExample(TenantsCustomersBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_customers_base
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    int deleteByPrimaryKey(Integer customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_customers_base
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    int insert(TenantsCustomersBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_customers_base
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    int insertSelective(TenantsCustomersBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_customers_base
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    List<TenantsCustomersBase> selectByExample(TenantsCustomersBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_customers_base
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    TenantsCustomersBase selectByPrimaryKey(Integer customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_customers_base
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    int updateByExampleSelective(@Param("record") TenantsCustomersBase record, @Param("example") TenantsCustomersBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_customers_base
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    int updateByExample(@Param("record") TenantsCustomersBase record, @Param("example") TenantsCustomersBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_customers_base
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    int updateByPrimaryKeySelective(TenantsCustomersBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_customers_base
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    int updateByPrimaryKey(TenantsCustomersBase record);
    
    
/*
	//总控平台开始
  *//** 
   * 总控平台-客户管理数量查询
     * @param map
     * @return
     *//*
    Integer getzkCustomerQueryCount(Map<String, Object> map);

    *//**
     * 总控平台-返回用户集合
     * @param map
     * @return
     *//*
    List<TenantsCustomersBaseEntity> getzkCustomerQueryList(Map<String, Object> map);
    //总控平台结束
*/
 
    
  
   
    
    
    
}