package com.fbee.modules.mybatis.dao;

import com.fbee.modules.core.persistence.annotation.MyBatisDao;
import com.fbee.modules.mybatis.model.TenantsApplication;
import com.fbee.modules.mybatis.model.TenantsApplicationExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
@MyBatisDao
public interface TenantsApplicationMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_application
	 * @mbggenerated  Thu Apr 27 14:21:10 CST 2017
	 */
	int countByExample(TenantsApplicationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_application
	 * @mbggenerated  Thu Apr 27 14:21:10 CST 2017
	 */
	int deleteByExample(TenantsApplicationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_application
	 * @mbggenerated  Thu Apr 27 14:21:10 CST 2017
	 */
	int deleteByPrimaryKey(Integer applicationId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_application
	 * @mbggenerated  Thu Apr 27 14:21:10 CST 2017
	 */
	int insert(TenantsApplication record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_application
	 * @mbggenerated  Thu Apr 27 14:21:10 CST 2017
	 */
	int insertSelective(TenantsApplication record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_application
	 * @mbggenerated  Thu Apr 27 14:21:10 CST 2017
	 */
	List<TenantsApplication> selectByExample(TenantsApplicationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_application
	 * @mbggenerated  Thu Apr 27 14:21:10 CST 2017
	 */
	TenantsApplication selectByPrimaryKey(Integer applicationId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_application
	 * @mbggenerated  Thu Apr 27 14:21:10 CST 2017
	 */
	int updateByExampleSelective(@Param("record") TenantsApplication record,
			@Param("example") TenantsApplicationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_application
	 * @mbggenerated  Thu Apr 27 14:21:10 CST 2017
	 */
	int updateByExample(@Param("record") TenantsApplication record,
			@Param("example") TenantsApplicationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_application
	 * @mbggenerated  Thu Apr 27 14:21:10 CST 2017
	 */
	int updateByPrimaryKeySelective(TenantsApplication record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_application
	 * @mbggenerated  Thu Apr 27 14:21:10 CST 2017
	 */
	int updateByPrimaryKey(TenantsApplication record);

	/**
	 * 申请入驻门店总数查询
	 * @param map
	 * @return
	 */
	Integer getTenantsInfoCount(Map<Object, Object> map);
	
	/**
	 * 申请入驻门店列表查询
	 * @param map
	 * @return
	 */
	List<Map>  getTenantsInfoList(Map<Object, Object> map);
	
	
	
	
    
}