package com.fbee.modules.mybatis.dao;

import com.fbee.modules.core.persistence.CrudDao;
import com.fbee.modules.core.persistence.annotation.MyBatisDao;
import com.fbee.modules.mybatis.entity.TenantsBankCardsEntity;
import com.fbee.modules.mybatis.model.TenantsBankCards;
import com.fbee.modules.mybatis.model.TenantsBankCardsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@MyBatisDao
public interface TenantsBankCardsMapper extends CrudDao<TenantsBankCardsEntity>{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_bank_cards
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	int countByExample(TenantsBankCardsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_bank_cards
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	int deleteByExample(TenantsBankCardsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_bank_cards
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	int deleteByPrimaryKey(Integer tenantId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_bank_cards
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	int insert(TenantsBankCards record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_bank_cards
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	int insertSelective(TenantsBankCards record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_bank_cards
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	List<TenantsBankCards> selectByExample(TenantsBankCardsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_bank_cards
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	TenantsBankCards selectByPrimaryKey(Integer tenantId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_bank_cards
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	int updateByExampleSelective(@Param("record") TenantsBankCards record,
			@Param("example") TenantsBankCardsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_bank_cards
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	int updateByExample(@Param("record") TenantsBankCards record, @Param("example") TenantsBankCardsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_bank_cards
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	int updateByPrimaryKeySelective(TenantsBankCards record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_bank_cards
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	int updateByPrimaryKey(TenantsBankCards record);
}