package com.fbee.modules.mybatis.dao;

import com.fbee.modules.core.persistence.annotation.MyBatisDao;
import com.fbee.modules.mybatis.model.tenantsFlow;
import com.fbee.modules.mybatis.model.tenantsFlowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
@MyBatisDao
public interface tenantsFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_flow
     *
     * @mbggenerated Mon Jul 03 13:19:38 CST 2017
     */
    int countByExample(tenantsFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_flow
     *
     * @mbggenerated Mon Jul 03 13:19:38 CST 2017
     */
    int deleteByExample(tenantsFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_flow
     *
     * @mbggenerated Mon Jul 03 13:19:38 CST 2017
     */
    int deleteByPrimaryKey(String tradeFlowNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_flow
     *
     * @mbggenerated Mon Jul 03 13:19:38 CST 2017
     */
    int insert(tenantsFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_flow
     *
     * @mbggenerated Mon Jul 03 13:19:38 CST 2017
     */
    int insertSelective(tenantsFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_flow
     *
     * @mbggenerated Mon Jul 03 13:19:38 CST 2017
     */
    List<tenantsFlow> selectByExample(tenantsFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_flow
     *
     * @mbggenerated Mon Jul 03 13:19:38 CST 2017
     */
    tenantsFlow selectByPrimaryKey(String tradeFlowNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_flow
     *
     * @mbggenerated Mon Jul 03 13:19:38 CST 2017
     */
    int updateByExampleSelective(@Param("record") tenantsFlow record, @Param("example") tenantsFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_flow
     *
     * @mbggenerated Mon Jul 03 13:19:38 CST 2017
     */
    int updateByExample(@Param("record") tenantsFlow record, @Param("example") tenantsFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_flow
     *
     * @mbggenerated Mon Jul 03 13:19:38 CST 2017
     */
    int updateByPrimaryKeySelective(tenantsFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenants_flow
     *
     * @mbggenerated Mon Jul 03 13:19:38 CST 2017
     */
    int updateByPrimaryKey(tenantsFlow record);
    
    
    //根据订单编号获取支付定金的支付流水号
    tenantsFlow getByOrderNo(String orderNo);
    
}