package com.fbee.modules.mybatis.model;

public class Bank {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bank.BANK_CODE
	 * @mbggenerated  Tue May 02 11:55:10 CST 2017
	 */
	private String bankCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bank.SYS_CODE
	 * @mbggenerated  Tue May 02 11:55:10 CST 2017
	 */
	private String sysCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bank.BANK_NAME
	 * @mbggenerated  Tue May 02 11:55:10 CST 2017
	 */
	private String bankName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bank.BANK_TYPECODE
	 * @mbggenerated  Tue May 02 11:55:10 CST 2017
	 */
	private String bankTypecode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bank.BANK_TYPENAME
	 * @mbggenerated  Tue May 02 11:55:10 CST 2017
	 */
	private String bankTypename;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bank.BANK_CODE
	 * @return  the value of bank.BANK_CODE
	 * @mbggenerated  Tue May 02 11:55:10 CST 2017
	 */
	public String getBankCode() {
		return bankCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bank.BANK_CODE
	 * @param bankCode  the value for bank.BANK_CODE
	 * @mbggenerated  Tue May 02 11:55:10 CST 2017
	 */
	public void setBankCode(String bankCode) {
		this.bankCode = bankCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bank.SYS_CODE
	 * @return  the value of bank.SYS_CODE
	 * @mbggenerated  Tue May 02 11:55:10 CST 2017
	 */
	public String getSysCode() {
		return sysCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bank.SYS_CODE
	 * @param sysCode  the value for bank.SYS_CODE
	 * @mbggenerated  Tue May 02 11:55:10 CST 2017
	 */
	public void setSysCode(String sysCode) {
		this.sysCode = sysCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bank.BANK_NAME
	 * @return  the value of bank.BANK_NAME
	 * @mbggenerated  Tue May 02 11:55:10 CST 2017
	 */
	public String getBankName() {
		return bankName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bank.BANK_NAME
	 * @param bankName  the value for bank.BANK_NAME
	 * @mbggenerated  Tue May 02 11:55:10 CST 2017
	 */
	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bank.BANK_TYPECODE
	 * @return  the value of bank.BANK_TYPECODE
	 * @mbggenerated  Tue May 02 11:55:10 CST 2017
	 */
	public String getBankTypecode() {
		return bankTypecode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bank.BANK_TYPECODE
	 * @param bankTypecode  the value for bank.BANK_TYPECODE
	 * @mbggenerated  Tue May 02 11:55:10 CST 2017
	 */
	public void setBankTypecode(String bankTypecode) {
		this.bankTypecode = bankTypecode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bank.BANK_TYPENAME
	 * @return  the value of bank.BANK_TYPENAME
	 * @mbggenerated  Tue May 02 11:55:10 CST 2017
	 */
	public String getBankTypename() {
		return bankTypename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bank.BANK_TYPENAME
	 * @param bankTypename  the value for bank.BANK_TYPENAME
	 * @mbggenerated  Tue May 02 11:55:10 CST 2017
	 */
	public void setBankTypename(String bankTypename) {
		this.bankTypename = bankTypename;
	}
}