package com.fbee.modules.mybatis.model;

import java.util.Date;

public class CertsInfo extends CertsInfoKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column certs_info.name
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column certs_info.idcard_img
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	private String idcardImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column certs_info.sex
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	private String sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column certs_info.Identification_name
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	private String identificationName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column certs_info.certification_date
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	private Date certificationDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column certs_info.certNo
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	private String certno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column certs_info.rate
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	private String rate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column certs_info.tgrade
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	private String tgrade;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column certs_info.skillGrade
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	private String skillgrade;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column certs_info.compGrade
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	private String compgrade;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column certs_info.abliyGrade
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	private String abliygrade;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column certs_info.result
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	private String result;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column certs_info.add_time
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	private Date addTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column certs_info.add_account
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	private String addAccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column certs_info.modify_time
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	private Date modifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column certs_info.modify_account
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	private String modifyAccount;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column certs_info.name
	 * @return  the value of certs_info.name
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column certs_info.name
	 * @param name  the value for certs_info.name
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column certs_info.idcard_img
	 * @return  the value of certs_info.idcard_img
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	public String getIdcardImg() {
		return idcardImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column certs_info.idcard_img
	 * @param idcardImg  the value for certs_info.idcard_img
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	public void setIdcardImg(String idcardImg) {
		this.idcardImg = idcardImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column certs_info.sex
	 * @return  the value of certs_info.sex
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column certs_info.sex
	 * @param sex  the value for certs_info.sex
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column certs_info.Identification_name
	 * @return  the value of certs_info.Identification_name
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	public String getIdentificationName() {
		return identificationName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column certs_info.Identification_name
	 * @param identificationName  the value for certs_info.Identification_name
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	public void setIdentificationName(String identificationName) {
		this.identificationName = identificationName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column certs_info.certification_date
	 * @return  the value of certs_info.certification_date
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	public Date getCertificationDate() {
		return certificationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column certs_info.certification_date
	 * @param certificationDate  the value for certs_info.certification_date
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	public void setCertificationDate(Date certificationDate) {
		this.certificationDate = certificationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column certs_info.certNo
	 * @return  the value of certs_info.certNo
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	public String getCertno() {
		return certno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column certs_info.certNo
	 * @param certno  the value for certs_info.certNo
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	public void setCertno(String certno) {
		this.certno = certno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column certs_info.rate
	 * @return  the value of certs_info.rate
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	public String getRate() {
		return rate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column certs_info.rate
	 * @param rate  the value for certs_info.rate
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	public void setRate(String rate) {
		this.rate = rate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column certs_info.tgrade
	 * @return  the value of certs_info.tgrade
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	public String getTgrade() {
		return tgrade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column certs_info.tgrade
	 * @param tgrade  the value for certs_info.tgrade
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	public void setTgrade(String tgrade) {
		this.tgrade = tgrade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column certs_info.skillGrade
	 * @return  the value of certs_info.skillGrade
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	public String getSkillgrade() {
		return skillgrade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column certs_info.skillGrade
	 * @param skillgrade  the value for certs_info.skillGrade
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	public void setSkillgrade(String skillgrade) {
		this.skillgrade = skillgrade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column certs_info.compGrade
	 * @return  the value of certs_info.compGrade
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	public String getCompgrade() {
		return compgrade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column certs_info.compGrade
	 * @param compgrade  the value for certs_info.compGrade
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	public void setCompgrade(String compgrade) {
		this.compgrade = compgrade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column certs_info.abliyGrade
	 * @return  the value of certs_info.abliyGrade
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	public String getAbliygrade() {
		return abliygrade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column certs_info.abliyGrade
	 * @param abliygrade  the value for certs_info.abliyGrade
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	public void setAbliygrade(String abliygrade) {
		this.abliygrade = abliygrade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column certs_info.result
	 * @return  the value of certs_info.result
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	public String getResult() {
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column certs_info.result
	 * @param result  the value for certs_info.result
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	public void setResult(String result) {
		this.result = result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column certs_info.add_time
	 * @return  the value of certs_info.add_time
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column certs_info.add_time
	 * @param addTime  the value for certs_info.add_time
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column certs_info.add_account
	 * @return  the value of certs_info.add_account
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	public String getAddAccount() {
		return addAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column certs_info.add_account
	 * @param addAccount  the value for certs_info.add_account
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	public void setAddAccount(String addAccount) {
		this.addAccount = addAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column certs_info.modify_time
	 * @return  the value of certs_info.modify_time
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column certs_info.modify_time
	 * @param modifyTime  the value for certs_info.modify_time
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column certs_info.modify_account
	 * @return  the value of certs_info.modify_account
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	public String getModifyAccount() {
		return modifyAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column certs_info.modify_account
	 * @param modifyAccount  the value for certs_info.modify_account
	 * @mbggenerated  Mon Mar 27 15:54:59 CST 2017
	 */
	public void setModifyAccount(String modifyAccount) {
		this.modifyAccount = modifyAccount;
	}
}