package com.fbee.modules.mybatis.model;

public class CertsInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certs_info.id
     *
     * @mbggenerated Mon Mar 27 15:54:59 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certs_info.idcard
     *
     * @mbggenerated Mon Mar 27 15:54:59 CST 2017
     */
    private String idcard;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certs_info.id
     *
     * @return the value of certs_info.id
     *
     * @mbggenerated Mon Mar 27 15:54:59 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certs_info.id
     *
     * @param id the value for certs_info.id
     *
     * @mbggenerated Mon Mar 27 15:54:59 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certs_info.idcard
     *
     * @return the value of certs_info.idcard
     *
     * @mbggenerated Mon Mar 27 15:54:59 CST 2017
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certs_info.idcard
     *
     * @param idcard the value for certs_info.idcard
     *
     * @mbggenerated Mon Mar 27 15:54:59 CST 2017
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }
}