package com.fbee.modules.mybatis.model;

import java.io.Serializable;
import java.util.Date;

public class MembersInfo implements Serializable{
    
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members_info.ID
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members_info.name
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members_info.mobile
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members_info.provice
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	private String provice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members_info.city
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	private String city;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members_info.county
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	private String county;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members_info.address
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members_info.weixin
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	private String weixin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members_info.qq
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	private String qq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members_info.sex
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	private String sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members_info.salt
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	private String salt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members_info.login_password
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	private String loginPassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members_info.user_status
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	private String userStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members_info.open_id
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	private String openId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members_info.register_time
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	private Date registerTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members_info.pwd_try_count
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	private Integer pwdTryCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members_info.is_locked
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	private String isLocked;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members_info.lock_time
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	private Date lockTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members_info.last_login_time
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	private Date lastLoginTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members_info.add_time
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	private Date addTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members_info.modify_time
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	private Date modifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members_info.first_wrong_time
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	private Date firstWrongTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members_info.is_usable
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	private String isUsable;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members_info.ID
	 * @return  the value of members_info.ID
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members_info.ID
	 * @param id  the value for members_info.ID
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members_info.name
	 * @return  the value of members_info.name
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members_info.name
	 * @param name  the value for members_info.name
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members_info.mobile
	 * @return  the value of members_info.mobile
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members_info.mobile
	 * @param mobile  the value for members_info.mobile
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members_info.provice
	 * @return  the value of members_info.provice
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public String getProvice() {
		return provice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members_info.provice
	 * @param provice  the value for members_info.provice
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public void setProvice(String provice) {
		this.provice = provice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members_info.city
	 * @return  the value of members_info.city
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members_info.city
	 * @param city  the value for members_info.city
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members_info.county
	 * @return  the value of members_info.county
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public String getCounty() {
		return county;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members_info.county
	 * @param county  the value for members_info.county
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public void setCounty(String county) {
		this.county = county;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members_info.address
	 * @return  the value of members_info.address
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members_info.address
	 * @param address  the value for members_info.address
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members_info.weixin
	 * @return  the value of members_info.weixin
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public String getWeixin() {
		return weixin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members_info.weixin
	 * @param weixin  the value for members_info.weixin
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public void setWeixin(String weixin) {
		this.weixin = weixin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members_info.qq
	 * @return  the value of members_info.qq
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public String getQq() {
		return qq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members_info.qq
	 * @param qq  the value for members_info.qq
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public void setQq(String qq) {
		this.qq = qq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members_info.sex
	 * @return  the value of members_info.sex
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members_info.sex
	 * @param sex  the value for members_info.sex
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members_info.salt
	 * @return  the value of members_info.salt
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public String getSalt() {
		return salt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members_info.salt
	 * @param salt  the value for members_info.salt
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public void setSalt(String salt) {
		this.salt = salt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members_info.login_password
	 * @return  the value of members_info.login_password
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public String getLoginPassword() {
		return loginPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members_info.login_password
	 * @param loginPassword  the value for members_info.login_password
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public void setLoginPassword(String loginPassword) {
		this.loginPassword = loginPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members_info.user_status
	 * @return  the value of members_info.user_status
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public String getUserStatus() {
		return userStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members_info.user_status
	 * @param userStatus  the value for members_info.user_status
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public void setUserStatus(String userStatus) {
		this.userStatus = userStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members_info.open_id
	 * @return  the value of members_info.open_id
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public String getOpenId() {
		return openId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members_info.open_id
	 * @param openId  the value for members_info.open_id
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public void setOpenId(String openId) {
		this.openId = openId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members_info.register_time
	 * @return  the value of members_info.register_time
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public Date getRegisterTime() {
		return registerTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members_info.register_time
	 * @param registerTime  the value for members_info.register_time
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public void setRegisterTime(Date registerTime) {
		this.registerTime = registerTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members_info.pwd_try_count
	 * @return  the value of members_info.pwd_try_count
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public Integer getPwdTryCount() {
		return pwdTryCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members_info.pwd_try_count
	 * @param pwdTryCount  the value for members_info.pwd_try_count
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public void setPwdTryCount(Integer pwdTryCount) {
		this.pwdTryCount = pwdTryCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members_info.is_locked
	 * @return  the value of members_info.is_locked
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public String getIsLocked() {
		return isLocked;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members_info.is_locked
	 * @param isLocked  the value for members_info.is_locked
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public void setIsLocked(String isLocked) {
		this.isLocked = isLocked;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members_info.lock_time
	 * @return  the value of members_info.lock_time
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public Date getLockTime() {
		return lockTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members_info.lock_time
	 * @param lockTime  the value for members_info.lock_time
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public void setLockTime(Date lockTime) {
		this.lockTime = lockTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members_info.last_login_time
	 * @return  the value of members_info.last_login_time
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public Date getLastLoginTime() {
		return lastLoginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members_info.last_login_time
	 * @param lastLoginTime  the value for members_info.last_login_time
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members_info.add_time
	 * @return  the value of members_info.add_time
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members_info.add_time
	 * @param addTime  the value for members_info.add_time
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members_info.modify_time
	 * @return  the value of members_info.modify_time
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members_info.modify_time
	 * @param modifyTime  the value for members_info.modify_time
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members_info.first_wrong_time
	 * @return  the value of members_info.first_wrong_time
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public Date getFirstWrongTime() {
		return firstWrongTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members_info.first_wrong_time
	 * @param firstWrongTime  the value for members_info.first_wrong_time
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public void setFirstWrongTime(Date firstWrongTime) {
		this.firstWrongTime = firstWrongTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members_info.is_usable
	 * @return  the value of members_info.is_usable
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public String getIsUsable() {
		return isUsable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members_info.is_usable
	 * @param isUsable  the value for members_info.is_usable
	 * @mbggenerated  Tue Mar 14 11:10:33 CST 2017
	 */
	public void setIsUsable(String isUsable) {
		this.isUsable = isUsable;
	}
}