package com.fbee.modules.mybatis.model;

import java.util.Date;

public class OrderChangeStaffInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_change_staff_info.ID
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_change_staff_info.ORDER_NO
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_change_staff_info.CUSTOMER_REMARK
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    private String customerRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_change_staff_info.CHANGE_STAFF
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    private Integer changeStaff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_change_staff_info.TENANT_REMARK
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    private String tenantRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_change_staff_info.DEAL_STATUS
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    private String dealStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_change_staff_info.add_time
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_change_staff_info.add_account
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    private String addAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_change_staff_info.modify_time
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_change_staff_info.modify_account
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    private String modifyAccount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_change_staff_info.ID
     *
     * @return the value of order_change_staff_info.ID
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_change_staff_info.ID
     *
     * @param id the value for order_change_staff_info.ID
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_change_staff_info.ORDER_NO
     *
     * @return the value of order_change_staff_info.ORDER_NO
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_change_staff_info.ORDER_NO
     *
     * @param orderNo the value for order_change_staff_info.ORDER_NO
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_change_staff_info.CUSTOMER_REMARK
     *
     * @return the value of order_change_staff_info.CUSTOMER_REMARK
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public String getCustomerRemark() {
        return customerRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_change_staff_info.CUSTOMER_REMARK
     *
     * @param customerRemark the value for order_change_staff_info.CUSTOMER_REMARK
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void setCustomerRemark(String customerRemark) {
        this.customerRemark = customerRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_change_staff_info.CHANGE_STAFF
     *
     * @return the value of order_change_staff_info.CHANGE_STAFF
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public Integer getChangeStaff() {
        return changeStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_change_staff_info.CHANGE_STAFF
     *
     * @param changeStaff the value for order_change_staff_info.CHANGE_STAFF
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void setChangeStaff(Integer changeStaff) {
        this.changeStaff = changeStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_change_staff_info.TENANT_REMARK
     *
     * @return the value of order_change_staff_info.TENANT_REMARK
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public String getTenantRemark() {
        return tenantRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_change_staff_info.TENANT_REMARK
     *
     * @param tenantRemark the value for order_change_staff_info.TENANT_REMARK
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void setTenantRemark(String tenantRemark) {
        this.tenantRemark = tenantRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_change_staff_info.DEAL_STATUS
     *
     * @return the value of order_change_staff_info.DEAL_STATUS
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public String getDealStatus() {
        return dealStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_change_staff_info.DEAL_STATUS
     *
     * @param dealStatus the value for order_change_staff_info.DEAL_STATUS
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void setDealStatus(String dealStatus) {
        this.dealStatus = dealStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_change_staff_info.add_time
     *
     * @return the value of order_change_staff_info.add_time
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_change_staff_info.add_time
     *
     * @param addTime the value for order_change_staff_info.add_time
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_change_staff_info.add_account
     *
     * @return the value of order_change_staff_info.add_account
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public String getAddAccount() {
        return addAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_change_staff_info.add_account
     *
     * @param addAccount the value for order_change_staff_info.add_account
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void setAddAccount(String addAccount) {
        this.addAccount = addAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_change_staff_info.modify_time
     *
     * @return the value of order_change_staff_info.modify_time
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_change_staff_info.modify_time
     *
     * @param modifyTime the value for order_change_staff_info.modify_time
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_change_staff_info.modify_account
     *
     * @return the value of order_change_staff_info.modify_account
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public String getModifyAccount() {
        return modifyAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_change_staff_info.modify_account
     *
     * @param modifyAccount the value for order_change_staff_info.modify_account
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void setModifyAccount(String modifyAccount) {
        this.modifyAccount = modifyAccount;
    }
}