package com.fbee.modules.mybatis.model;

import java.util.Date;

public class SystemUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.id
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.login_account
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    private String loginAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.login_name
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.password
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.salt
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.telephone
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.remarks
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.email
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.login_ip
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    private String loginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.login_time
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    private Date loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.is_usable
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    private String isUsable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.add_time
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.add_account
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    private String addAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.modify_time
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_user.modify_account
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    private String modifyAccount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.id
     *
     * @return the value of system_user.id
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.id
     *
     * @param id the value for system_user.id
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.login_account
     *
     * @return the value of system_user.login_account
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    public String getLoginAccount() {
        return loginAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.login_account
     *
     * @param loginAccount the value for system_user.login_account
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    public void setLoginAccount(String loginAccount) {
        this.loginAccount = loginAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.login_name
     *
     * @return the value of system_user.login_name
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.login_name
     *
     * @param loginName the value for system_user.login_name
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.password
     *
     * @return the value of system_user.password
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.password
     *
     * @param password the value for system_user.password
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.salt
     *
     * @return the value of system_user.salt
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.salt
     *
     * @param salt the value for system_user.salt
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.telephone
     *
     * @return the value of system_user.telephone
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.telephone
     *
     * @param telephone the value for system_user.telephone
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.remarks
     *
     * @return the value of system_user.remarks
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.remarks
     *
     * @param remarks the value for system_user.remarks
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.email
     *
     * @return the value of system_user.email
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.email
     *
     * @param email the value for system_user.email
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.login_ip
     *
     * @return the value of system_user.login_ip
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.login_ip
     *
     * @param loginIp the value for system_user.login_ip
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.login_time
     *
     * @return the value of system_user.login_time
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.login_time
     *
     * @param loginTime the value for system_user.login_time
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.is_usable
     *
     * @return the value of system_user.is_usable
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    public String getIsUsable() {
        return isUsable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.is_usable
     *
     * @param isUsable the value for system_user.is_usable
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    public void setIsUsable(String isUsable) {
        this.isUsable = isUsable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.add_time
     *
     * @return the value of system_user.add_time
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.add_time
     *
     * @param addTime the value for system_user.add_time
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.add_account
     *
     * @return the value of system_user.add_account
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    public String getAddAccount() {
        return addAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.add_account
     *
     * @param addAccount the value for system_user.add_account
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    public void setAddAccount(String addAccount) {
        this.addAccount = addAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.modify_time
     *
     * @return the value of system_user.modify_time
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.modify_time
     *
     * @param modifyTime the value for system_user.modify_time
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_user.modify_account
     *
     * @return the value of system_user.modify_account
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    public String getModifyAccount() {
        return modifyAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_user.modify_account
     *
     * @param modifyAccount the value for system_user.modify_account
     *
     * @mbggenerated Thu Mar 30 18:22:14 CST 2017
     */
    public void setModifyAccount(String modifyAccount) {
        this.modifyAccount = modifyAccount;
    }
}