package com.fbee.modules.mybatis.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TenantsFunds implements Serializable{
    
	private static final long serialVersionUID = 1L;

	/**
     * 表：tenants_funds
     * 字段：TENANT_ID
     * 注释：租户id
     *
     * @mbggenerated
     */
    private Integer tenantId;

    /**
     * 表：tenants_funds
     * 字段：GRAND_TOTAL_AMOUNT
     * 注释：租户账户累计金额
     *
     * @mbggenerated
     */
    private BigDecimal grandTotalAmount;

    /**
     * 表：tenants_funds
     * 字段：TOTAL_AMOUNT
     * 注释：租户账户总额
     *
     * @mbggenerated
     */
    private BigDecimal totalAmount;

    /**
     * 表：tenants_funds
     * 字段：FROZEN_AMOUNT
     * 注释：租户账户冻结额度
     *
     * @mbggenerated
     */
    private BigDecimal frozenAmount;

    /**
     * 表：tenants_funds
     * 字段：AVAILABLE_AMOUNT
     * 注释：租户账户可用额度
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_finance_records.add_account
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    private String addAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_finance_records.modify_time
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_finance_records.modify_account
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    private String modifyAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_finance_records.is_usable
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    private String isUsable;

    private BigDecimal availableAmount;

    public Integer getTenantId() {
        return tenantId;
    }

    public void setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
    }

    public BigDecimal getGrandTotalAmount() {
        return grandTotalAmount;
    }

    public void setGrandTotalAmount(BigDecimal grandTotalAmount) {
        this.grandTotalAmount = grandTotalAmount;
    }

    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    public BigDecimal getFrozenAmount() {
        return frozenAmount;
    }

    public void setFrozenAmount(BigDecimal frozenAmount) {
        this.frozenAmount = frozenAmount;
    }

    public BigDecimal getAvailableAmount() {
        return availableAmount;
    }

    public void setAvailableAmount(BigDecimal availableAmount) {
        this.availableAmount = availableAmount;
    }

	public Date getAddTime() {
		return addTime;
	}

	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	public String getAddAccount() {
		return addAccount;
	}

	public void setAddAccount(String addAccount) {
		this.addAccount = addAccount;
	}

	public Date getModifyTime() {
		return modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	public String getModifyAccount() {
		return modifyAccount;
	}

	public void setModifyAccount(String modifyAccount) {
		this.modifyAccount = modifyAccount;
	}

	public String getIsUsable() {
		return isUsable;
	}

	public void setIsUsable(String isUsable) {
		this.isUsable = isUsable;
	}
}