package com.fbee.modules.mybatis.model;

import java.io.Serializable;
import java.util.Date;

public class TenantsBankCards implements Serializable{
    
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_bank_cards.TENANT_ID
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	private Integer tenantId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_bank_cards.CARD_NO
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	private String cardNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_bank_cards.account_Type
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	private String accountType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_bank_cards.BANK_NAME
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	private String bankName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_bank_cards.BANK_CODE
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	private String bankCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_bank_cards.BANK_SEC_NAME
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	private String bankSecName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_bank_cards.remarks
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	private String remarks;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_bank_cards.is_usable
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	private String isUsable;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_bank_cards.add_time
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	private Date addTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_bank_cards.add_account
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	private String addAccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_bank_cards.modify_time
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	private Date modifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenants_bank_cards.modify_account
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	private String modifyAccount;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_bank_cards.TENANT_ID
	 * @return  the value of tenants_bank_cards.TENANT_ID
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	public Integer getTenantId() {
		return tenantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_bank_cards.TENANT_ID
	 * @param tenantId  the value for tenants_bank_cards.TENANT_ID
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	public void setTenantId(Integer tenantId) {
		this.tenantId = tenantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_bank_cards.CARD_NO
	 * @return  the value of tenants_bank_cards.CARD_NO
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	public String getCardNo() {
		return cardNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_bank_cards.CARD_NO
	 * @param cardNo  the value for tenants_bank_cards.CARD_NO
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	public void setCardNo(String cardNo) {
		this.cardNo = cardNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_bank_cards.account_Type
	 * @return  the value of tenants_bank_cards.account_Type
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	public String getAccountType() {
		return accountType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_bank_cards.account_Type
	 * @param accountType  the value for tenants_bank_cards.account_Type
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	public void setAccountType(String accountType) {
		this.accountType = accountType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_bank_cards.BANK_NAME
	 * @return  the value of tenants_bank_cards.BANK_NAME
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	public String getBankName() {
		return bankName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_bank_cards.BANK_NAME
	 * @param bankName  the value for tenants_bank_cards.BANK_NAME
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_bank_cards.BANK_CODE
	 * @return  the value of tenants_bank_cards.BANK_CODE
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	public String getBankCode() {
		return bankCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_bank_cards.BANK_CODE
	 * @param bankCode  the value for tenants_bank_cards.BANK_CODE
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	public void setBankCode(String bankCode) {
		this.bankCode = bankCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_bank_cards.BANK_SEC_NAME
	 * @return  the value of tenants_bank_cards.BANK_SEC_NAME
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	public String getBankSecName() {
		return bankSecName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_bank_cards.BANK_SEC_NAME
	 * @param bankSecName  the value for tenants_bank_cards.BANK_SEC_NAME
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	public void setBankSecName(String bankSecName) {
		this.bankSecName = bankSecName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_bank_cards.remarks
	 * @return  the value of tenants_bank_cards.remarks
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_bank_cards.remarks
	 * @param remarks  the value for tenants_bank_cards.remarks
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_bank_cards.is_usable
	 * @return  the value of tenants_bank_cards.is_usable
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	public String getIsUsable() {
		return isUsable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_bank_cards.is_usable
	 * @param isUsable  the value for tenants_bank_cards.is_usable
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	public void setIsUsable(String isUsable) {
		this.isUsable = isUsable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_bank_cards.add_time
	 * @return  the value of tenants_bank_cards.add_time
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_bank_cards.add_time
	 * @param addTime  the value for tenants_bank_cards.add_time
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_bank_cards.add_account
	 * @return  the value of tenants_bank_cards.add_account
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	public String getAddAccount() {
		return addAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_bank_cards.add_account
	 * @param addAccount  the value for tenants_bank_cards.add_account
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	public void setAddAccount(String addAccount) {
		this.addAccount = addAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_bank_cards.modify_time
	 * @return  the value of tenants_bank_cards.modify_time
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_bank_cards.modify_time
	 * @param modifyTime  the value for tenants_bank_cards.modify_time
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenants_bank_cards.modify_account
	 * @return  the value of tenants_bank_cards.modify_account
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	public String getModifyAccount() {
		return modifyAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenants_bank_cards.modify_account
	 * @param modifyAccount  the value for tenants_bank_cards.modify_account
	 * @mbggenerated  Wed Apr 19 09:30:13 CST 2017
	 */
	public void setModifyAccount(String modifyAccount) {
		this.modifyAccount = modifyAccount;
	}

	private static final long serialVersionUID = 1L;

	




}