package com.fbee.modules.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TenantsApplicationExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tenants_application
	 * @mbggenerated  Thu Apr 27 14:21:10 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tenants_application
	 * @mbggenerated  Thu Apr 27 14:21:10 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tenants_application
	 * @mbggenerated  Thu Apr 27 14:21:10 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_application
	 * @mbggenerated  Thu Apr 27 14:21:10 CST 2017
	 */
	public TenantsApplicationExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_application
	 * @mbggenerated  Thu Apr 27 14:21:10 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_application
	 * @mbggenerated  Thu Apr 27 14:21:10 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_application
	 * @mbggenerated  Thu Apr 27 14:21:10 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_application
	 * @mbggenerated  Thu Apr 27 14:21:10 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_application
	 * @mbggenerated  Thu Apr 27 14:21:10 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_application
	 * @mbggenerated  Thu Apr 27 14:21:10 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_application
	 * @mbggenerated  Thu Apr 27 14:21:10 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_application
	 * @mbggenerated  Thu Apr 27 14:21:10 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_application
	 * @mbggenerated  Thu Apr 27 14:21:10 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tenants_application
	 * @mbggenerated  Thu Apr 27 14:21:10 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tenants_application
	 * @mbggenerated  Thu Apr 27 14:21:10 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andApplicationIdIsNull() {
			addCriterion("Application_ID is null");
			return (Criteria) this;
		}

		public Criteria andApplicationIdIsNotNull() {
			addCriterion("Application_ID is not null");
			return (Criteria) this;
		}

		public Criteria andApplicationIdEqualTo(Integer value) {
			addCriterion("Application_ID =", value, "applicationId");
			return (Criteria) this;
		}

		public Criteria andApplicationIdNotEqualTo(Integer value) {
			addCriterion("Application_ID <>", value, "applicationId");
			return (Criteria) this;
		}

		public Criteria andApplicationIdGreaterThan(Integer value) {
			addCriterion("Application_ID >", value, "applicationId");
			return (Criteria) this;
		}

		public Criteria andApplicationIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("Application_ID >=", value, "applicationId");
			return (Criteria) this;
		}

		public Criteria andApplicationIdLessThan(Integer value) {
			addCriterion("Application_ID <", value, "applicationId");
			return (Criteria) this;
		}

		public Criteria andApplicationIdLessThanOrEqualTo(Integer value) {
			addCriterion("Application_ID <=", value, "applicationId");
			return (Criteria) this;
		}

		public Criteria andApplicationIdIn(List<Integer> values) {
			addCriterion("Application_ID in", values, "applicationId");
			return (Criteria) this;
		}

		public Criteria andApplicationIdNotIn(List<Integer> values) {
			addCriterion("Application_ID not in", values, "applicationId");
			return (Criteria) this;
		}

		public Criteria andApplicationIdBetween(Integer value1, Integer value2) {
			addCriterion("Application_ID between", value1, value2, "applicationId");
			return (Criteria) this;
		}

		public Criteria andApplicationIdNotBetween(Integer value1, Integer value2) {
			addCriterion("Application_ID not between", value1, value2, "applicationId");
			return (Criteria) this;
		}

		public Criteria andTenantNameIsNull() {
			addCriterion("TENANT_NAME is null");
			return (Criteria) this;
		}

		public Criteria andTenantNameIsNotNull() {
			addCriterion("TENANT_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andTenantNameEqualTo(String value) {
			addCriterion("TENANT_NAME =", value, "tenantName");
			return (Criteria) this;
		}

		public Criteria andTenantNameNotEqualTo(String value) {
			addCriterion("TENANT_NAME <>", value, "tenantName");
			return (Criteria) this;
		}

		public Criteria andTenantNameGreaterThan(String value) {
			addCriterion("TENANT_NAME >", value, "tenantName");
			return (Criteria) this;
		}

		public Criteria andTenantNameGreaterThanOrEqualTo(String value) {
			addCriterion("TENANT_NAME >=", value, "tenantName");
			return (Criteria) this;
		}

		public Criteria andTenantNameLessThan(String value) {
			addCriterion("TENANT_NAME <", value, "tenantName");
			return (Criteria) this;
		}

		public Criteria andTenantNameLessThanOrEqualTo(String value) {
			addCriterion("TENANT_NAME <=", value, "tenantName");
			return (Criteria) this;
		}

		public Criteria andTenantNameLike(String value) {
			addCriterion("TENANT_NAME like", value, "tenantName");
			return (Criteria) this;
		}

		public Criteria andTenantNameNotLike(String value) {
			addCriterion("TENANT_NAME not like", value, "tenantName");
			return (Criteria) this;
		}

		public Criteria andTenantNameIn(List<String> values) {
			addCriterion("TENANT_NAME in", values, "tenantName");
			return (Criteria) this;
		}

		public Criteria andTenantNameNotIn(List<String> values) {
			addCriterion("TENANT_NAME not in", values, "tenantName");
			return (Criteria) this;
		}

		public Criteria andTenantNameBetween(String value1, String value2) {
			addCriterion("TENANT_NAME between", value1, value2, "tenantName");
			return (Criteria) this;
		}

		public Criteria andTenantNameNotBetween(String value1, String value2) {
			addCriterion("TENANT_NAME not between", value1, value2, "tenantName");
			return (Criteria) this;
		}

		public Criteria andRegisterPhoneIsNull() {
			addCriterion("REGISTER_PHONE is null");
			return (Criteria) this;
		}

		public Criteria andRegisterPhoneIsNotNull() {
			addCriterion("REGISTER_PHONE is not null");
			return (Criteria) this;
		}

		public Criteria andRegisterPhoneEqualTo(String value) {
			addCriterion("REGISTER_PHONE =", value, "registerPhone");
			return (Criteria) this;
		}

		public Criteria andRegisterPhoneNotEqualTo(String value) {
			addCriterion("REGISTER_PHONE <>", value, "registerPhone");
			return (Criteria) this;
		}

		public Criteria andRegisterPhoneGreaterThan(String value) {
			addCriterion("REGISTER_PHONE >", value, "registerPhone");
			return (Criteria) this;
		}

		public Criteria andRegisterPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("REGISTER_PHONE >=", value, "registerPhone");
			return (Criteria) this;
		}

		public Criteria andRegisterPhoneLessThan(String value) {
			addCriterion("REGISTER_PHONE <", value, "registerPhone");
			return (Criteria) this;
		}

		public Criteria andRegisterPhoneLessThanOrEqualTo(String value) {
			addCriterion("REGISTER_PHONE <=", value, "registerPhone");
			return (Criteria) this;
		}

		public Criteria andRegisterPhoneLike(String value) {
			addCriterion("REGISTER_PHONE like", value, "registerPhone");
			return (Criteria) this;
		}

		public Criteria andRegisterPhoneNotLike(String value) {
			addCriterion("REGISTER_PHONE not like", value, "registerPhone");
			return (Criteria) this;
		}

		public Criteria andRegisterPhoneIn(List<String> values) {
			addCriterion("REGISTER_PHONE in", values, "registerPhone");
			return (Criteria) this;
		}

		public Criteria andRegisterPhoneNotIn(List<String> values) {
			addCriterion("REGISTER_PHONE not in", values, "registerPhone");
			return (Criteria) this;
		}

		public Criteria andRegisterPhoneBetween(String value1, String value2) {
			addCriterion("REGISTER_PHONE between", value1, value2, "registerPhone");
			return (Criteria) this;
		}

		public Criteria andRegisterPhoneNotBetween(String value1, String value2) {
			addCriterion("REGISTER_PHONE not between", value1, value2, "registerPhone");
			return (Criteria) this;
		}

		public Criteria andTenantStatusIsNull() {
			addCriterion("TENANT_STATUS is null");
			return (Criteria) this;
		}

		public Criteria andTenantStatusIsNotNull() {
			addCriterion("TENANT_STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andTenantStatusEqualTo(String value) {
			addCriterion("TENANT_STATUS =", value, "tenantStatus");
			return (Criteria) this;
		}

		public Criteria andTenantStatusNotEqualTo(String value) {
			addCriterion("TENANT_STATUS <>", value, "tenantStatus");
			return (Criteria) this;
		}

		public Criteria andTenantStatusGreaterThan(String value) {
			addCriterion("TENANT_STATUS >", value, "tenantStatus");
			return (Criteria) this;
		}

		public Criteria andTenantStatusGreaterThanOrEqualTo(String value) {
			addCriterion("TENANT_STATUS >=", value, "tenantStatus");
			return (Criteria) this;
		}

		public Criteria andTenantStatusLessThan(String value) {
			addCriterion("TENANT_STATUS <", value, "tenantStatus");
			return (Criteria) this;
		}

		public Criteria andTenantStatusLessThanOrEqualTo(String value) {
			addCriterion("TENANT_STATUS <=", value, "tenantStatus");
			return (Criteria) this;
		}

		public Criteria andTenantStatusLike(String value) {
			addCriterion("TENANT_STATUS like", value, "tenantStatus");
			return (Criteria) this;
		}

		public Criteria andTenantStatusNotLike(String value) {
			addCriterion("TENANT_STATUS not like", value, "tenantStatus");
			return (Criteria) this;
		}

		public Criteria andTenantStatusIn(List<String> values) {
			addCriterion("TENANT_STATUS in", values, "tenantStatus");
			return (Criteria) this;
		}

		public Criteria andTenantStatusNotIn(List<String> values) {
			addCriterion("TENANT_STATUS not in", values, "tenantStatus");
			return (Criteria) this;
		}

		public Criteria andTenantStatusBetween(String value1, String value2) {
			addCriterion("TENANT_STATUS between", value1, value2, "tenantStatus");
			return (Criteria) this;
		}

		public Criteria andTenantStatusNotBetween(String value1, String value2) {
			addCriterion("TENANT_STATUS not between", value1, value2, "tenantStatus");
			return (Criteria) this;
		}

		public Criteria andPrivinceIsNull() {
			addCriterion("privince is null");
			return (Criteria) this;
		}

		public Criteria andPrivinceIsNotNull() {
			addCriterion("privince is not null");
			return (Criteria) this;
		}

		public Criteria andPrivinceEqualTo(String value) {
			addCriterion("privince =", value, "privince");
			return (Criteria) this;
		}

		public Criteria andPrivinceNotEqualTo(String value) {
			addCriterion("privince <>", value, "privince");
			return (Criteria) this;
		}

		public Criteria andPrivinceGreaterThan(String value) {
			addCriterion("privince >", value, "privince");
			return (Criteria) this;
		}

		public Criteria andPrivinceGreaterThanOrEqualTo(String value) {
			addCriterion("privince >=", value, "privince");
			return (Criteria) this;
		}

		public Criteria andPrivinceLessThan(String value) {
			addCriterion("privince <", value, "privince");
			return (Criteria) this;
		}

		public Criteria andPrivinceLessThanOrEqualTo(String value) {
			addCriterion("privince <=", value, "privince");
			return (Criteria) this;
		}

		public Criteria andPrivinceLike(String value) {
			addCriterion("privince like", value, "privince");
			return (Criteria) this;
		}

		public Criteria andPrivinceNotLike(String value) {
			addCriterion("privince not like", value, "privince");
			return (Criteria) this;
		}

		public Criteria andPrivinceIn(List<String> values) {
			addCriterion("privince in", values, "privince");
			return (Criteria) this;
		}

		public Criteria andPrivinceNotIn(List<String> values) {
			addCriterion("privince not in", values, "privince");
			return (Criteria) this;
		}

		public Criteria andPrivinceBetween(String value1, String value2) {
			addCriterion("privince between", value1, value2, "privince");
			return (Criteria) this;
		}

		public Criteria andPrivinceNotBetween(String value1, String value2) {
			addCriterion("privince not between", value1, value2, "privince");
			return (Criteria) this;
		}

		public Criteria andCityIsNull() {
			addCriterion("city is null");
			return (Criteria) this;
		}

		public Criteria andCityIsNotNull() {
			addCriterion("city is not null");
			return (Criteria) this;
		}

		public Criteria andCityEqualTo(String value) {
			addCriterion("city =", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotEqualTo(String value) {
			addCriterion("city <>", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityGreaterThan(String value) {
			addCriterion("city >", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityGreaterThanOrEqualTo(String value) {
			addCriterion("city >=", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityLessThan(String value) {
			addCriterion("city <", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityLessThanOrEqualTo(String value) {
			addCriterion("city <=", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityLike(String value) {
			addCriterion("city like", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotLike(String value) {
			addCriterion("city not like", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityIn(List<String> values) {
			addCriterion("city in", values, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotIn(List<String> values) {
			addCriterion("city not in", values, "city");
			return (Criteria) this;
		}

		public Criteria andCityBetween(String value1, String value2) {
			addCriterion("city between", value1, value2, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotBetween(String value1, String value2) {
			addCriterion("city not between", value1, value2, "city");
			return (Criteria) this;
		}

		public Criteria andAreaIsNull() {
			addCriterion("area is null");
			return (Criteria) this;
		}

		public Criteria andAreaIsNotNull() {
			addCriterion("area is not null");
			return (Criteria) this;
		}

		public Criteria andAreaEqualTo(String value) {
			addCriterion("area =", value, "area");
			return (Criteria) this;
		}

		public Criteria andAreaNotEqualTo(String value) {
			addCriterion("area <>", value, "area");
			return (Criteria) this;
		}

		public Criteria andAreaGreaterThan(String value) {
			addCriterion("area >", value, "area");
			return (Criteria) this;
		}

		public Criteria andAreaGreaterThanOrEqualTo(String value) {
			addCriterion("area >=", value, "area");
			return (Criteria) this;
		}

		public Criteria andAreaLessThan(String value) {
			addCriterion("area <", value, "area");
			return (Criteria) this;
		}

		public Criteria andAreaLessThanOrEqualTo(String value) {
			addCriterion("area <=", value, "area");
			return (Criteria) this;
		}

		public Criteria andAreaLike(String value) {
			addCriterion("area like", value, "area");
			return (Criteria) this;
		}

		public Criteria andAreaNotLike(String value) {
			addCriterion("area not like", value, "area");
			return (Criteria) this;
		}

		public Criteria andAreaIn(List<String> values) {
			addCriterion("area in", values, "area");
			return (Criteria) this;
		}

		public Criteria andAreaNotIn(List<String> values) {
			addCriterion("area not in", values, "area");
			return (Criteria) this;
		}

		public Criteria andAreaBetween(String value1, String value2) {
			addCriterion("area between", value1, value2, "area");
			return (Criteria) this;
		}

		public Criteria andAreaNotBetween(String value1, String value2) {
			addCriterion("area not between", value1, value2, "area");
			return (Criteria) this;
		}

		public Criteria andContactAddressIsNull() {
			addCriterion("CONTACT_ADDRESS is null");
			return (Criteria) this;
		}

		public Criteria andContactAddressIsNotNull() {
			addCriterion("CONTACT_ADDRESS is not null");
			return (Criteria) this;
		}

		public Criteria andContactAddressEqualTo(String value) {
			addCriterion("CONTACT_ADDRESS =", value, "contactAddress");
			return (Criteria) this;
		}

		public Criteria andContactAddressNotEqualTo(String value) {
			addCriterion("CONTACT_ADDRESS <>", value, "contactAddress");
			return (Criteria) this;
		}

		public Criteria andContactAddressGreaterThan(String value) {
			addCriterion("CONTACT_ADDRESS >", value, "contactAddress");
			return (Criteria) this;
		}

		public Criteria andContactAddressGreaterThanOrEqualTo(String value) {
			addCriterion("CONTACT_ADDRESS >=", value, "contactAddress");
			return (Criteria) this;
		}

		public Criteria andContactAddressLessThan(String value) {
			addCriterion("CONTACT_ADDRESS <", value, "contactAddress");
			return (Criteria) this;
		}

		public Criteria andContactAddressLessThanOrEqualTo(String value) {
			addCriterion("CONTACT_ADDRESS <=", value, "contactAddress");
			return (Criteria) this;
		}

		public Criteria andContactAddressLike(String value) {
			addCriterion("CONTACT_ADDRESS like", value, "contactAddress");
			return (Criteria) this;
		}

		public Criteria andContactAddressNotLike(String value) {
			addCriterion("CONTACT_ADDRESS not like", value, "contactAddress");
			return (Criteria) this;
		}

		public Criteria andContactAddressIn(List<String> values) {
			addCriterion("CONTACT_ADDRESS in", values, "contactAddress");
			return (Criteria) this;
		}

		public Criteria andContactAddressNotIn(List<String> values) {
			addCriterion("CONTACT_ADDRESS not in", values, "contactAddress");
			return (Criteria) this;
		}

		public Criteria andContactAddressBetween(String value1, String value2) {
			addCriterion("CONTACT_ADDRESS between", value1, value2, "contactAddress");
			return (Criteria) this;
		}

		public Criteria andContactAddressNotBetween(String value1, String value2) {
			addCriterion("CONTACT_ADDRESS not between", value1, value2, "contactAddress");
			return (Criteria) this;
		}

		public Criteria andAgentNameIsNull() {
			addCriterion("agent_name is null");
			return (Criteria) this;
		}

		public Criteria andAgentNameIsNotNull() {
			addCriterion("agent_name is not null");
			return (Criteria) this;
		}

		public Criteria andAgentNameEqualTo(String value) {
			addCriterion("agent_name =", value, "agentName");
			return (Criteria) this;
		}

		public Criteria andAgentNameNotEqualTo(String value) {
			addCriterion("agent_name <>", value, "agentName");
			return (Criteria) this;
		}

		public Criteria andAgentNameGreaterThan(String value) {
			addCriterion("agent_name >", value, "agentName");
			return (Criteria) this;
		}

		public Criteria andAgentNameGreaterThanOrEqualTo(String value) {
			addCriterion("agent_name >=", value, "agentName");
			return (Criteria) this;
		}

		public Criteria andAgentNameLessThan(String value) {
			addCriterion("agent_name <", value, "agentName");
			return (Criteria) this;
		}

		public Criteria andAgentNameLessThanOrEqualTo(String value) {
			addCriterion("agent_name <=", value, "agentName");
			return (Criteria) this;
		}

		public Criteria andAgentNameLike(String value) {
			addCriterion("agent_name like", value, "agentName");
			return (Criteria) this;
		}

		public Criteria andAgentNameNotLike(String value) {
			addCriterion("agent_name not like", value, "agentName");
			return (Criteria) this;
		}

		public Criteria andAgentNameIn(List<String> values) {
			addCriterion("agent_name in", values, "agentName");
			return (Criteria) this;
		}

		public Criteria andAgentNameNotIn(List<String> values) {
			addCriterion("agent_name not in", values, "agentName");
			return (Criteria) this;
		}

		public Criteria andAgentNameBetween(String value1, String value2) {
			addCriterion("agent_name between", value1, value2, "agentName");
			return (Criteria) this;
		}

		public Criteria andAgentNameNotBetween(String value1, String value2) {
			addCriterion("agent_name not between", value1, value2, "agentName");
			return (Criteria) this;
		}

		public Criteria andIdTypeIsNull() {
			addCriterion("id_type is null");
			return (Criteria) this;
		}

		public Criteria andIdTypeIsNotNull() {
			addCriterion("id_type is not null");
			return (Criteria) this;
		}

		public Criteria andIdTypeEqualTo(String value) {
			addCriterion("id_type =", value, "idType");
			return (Criteria) this;
		}

		public Criteria andIdTypeNotEqualTo(String value) {
			addCriterion("id_type <>", value, "idType");
			return (Criteria) this;
		}

		public Criteria andIdTypeGreaterThan(String value) {
			addCriterion("id_type >", value, "idType");
			return (Criteria) this;
		}

		public Criteria andIdTypeGreaterThanOrEqualTo(String value) {
			addCriterion("id_type >=", value, "idType");
			return (Criteria) this;
		}

		public Criteria andIdTypeLessThan(String value) {
			addCriterion("id_type <", value, "idType");
			return (Criteria) this;
		}

		public Criteria andIdTypeLessThanOrEqualTo(String value) {
			addCriterion("id_type <=", value, "idType");
			return (Criteria) this;
		}

		public Criteria andIdTypeLike(String value) {
			addCriterion("id_type like", value, "idType");
			return (Criteria) this;
		}

		public Criteria andIdTypeNotLike(String value) {
			addCriterion("id_type not like", value, "idType");
			return (Criteria) this;
		}

		public Criteria andIdTypeIn(List<String> values) {
			addCriterion("id_type in", values, "idType");
			return (Criteria) this;
		}

		public Criteria andIdTypeNotIn(List<String> values) {
			addCriterion("id_type not in", values, "idType");
			return (Criteria) this;
		}

		public Criteria andIdTypeBetween(String value1, String value2) {
			addCriterion("id_type between", value1, value2, "idType");
			return (Criteria) this;
		}

		public Criteria andIdTypeNotBetween(String value1, String value2) {
			addCriterion("id_type not between", value1, value2, "idType");
			return (Criteria) this;
		}

		public Criteria andIdNumberIsNull() {
			addCriterion("id_number is null");
			return (Criteria) this;
		}

		public Criteria andIdNumberIsNotNull() {
			addCriterion("id_number is not null");
			return (Criteria) this;
		}

		public Criteria andIdNumberEqualTo(String value) {
			addCriterion("id_number =", value, "idNumber");
			return (Criteria) this;
		}

		public Criteria andIdNumberNotEqualTo(String value) {
			addCriterion("id_number <>", value, "idNumber");
			return (Criteria) this;
		}

		public Criteria andIdNumberGreaterThan(String value) {
			addCriterion("id_number >", value, "idNumber");
			return (Criteria) this;
		}

		public Criteria andIdNumberGreaterThanOrEqualTo(String value) {
			addCriterion("id_number >=", value, "idNumber");
			return (Criteria) this;
		}

		public Criteria andIdNumberLessThan(String value) {
			addCriterion("id_number <", value, "idNumber");
			return (Criteria) this;
		}

		public Criteria andIdNumberLessThanOrEqualTo(String value) {
			addCriterion("id_number <=", value, "idNumber");
			return (Criteria) this;
		}

		public Criteria andIdNumberLike(String value) {
			addCriterion("id_number like", value, "idNumber");
			return (Criteria) this;
		}

		public Criteria andIdNumberNotLike(String value) {
			addCriterion("id_number not like", value, "idNumber");
			return (Criteria) this;
		}

		public Criteria andIdNumberIn(List<String> values) {
			addCriterion("id_number in", values, "idNumber");
			return (Criteria) this;
		}

		public Criteria andIdNumberNotIn(List<String> values) {
			addCriterion("id_number not in", values, "idNumber");
			return (Criteria) this;
		}

		public Criteria andIdNumberBetween(String value1, String value2) {
			addCriterion("id_number between", value1, value2, "idNumber");
			return (Criteria) this;
		}

		public Criteria andIdNumberNotBetween(String value1, String value2) {
			addCriterion("id_number not between", value1, value2, "idNumber");
			return (Criteria) this;
		}

		public Criteria andLicenceImgIsNull() {
			addCriterion("licence_img is null");
			return (Criteria) this;
		}

		public Criteria andLicenceImgIsNotNull() {
			addCriterion("licence_img is not null");
			return (Criteria) this;
		}

		public Criteria andLicenceImgEqualTo(String value) {
			addCriterion("licence_img =", value, "licenceImg");
			return (Criteria) this;
		}

		public Criteria andLicenceImgNotEqualTo(String value) {
			addCriterion("licence_img <>", value, "licenceImg");
			return (Criteria) this;
		}

		public Criteria andLicenceImgGreaterThan(String value) {
			addCriterion("licence_img >", value, "licenceImg");
			return (Criteria) this;
		}

		public Criteria andLicenceImgGreaterThanOrEqualTo(String value) {
			addCriterion("licence_img >=", value, "licenceImg");
			return (Criteria) this;
		}

		public Criteria andLicenceImgLessThan(String value) {
			addCriterion("licence_img <", value, "licenceImg");
			return (Criteria) this;
		}

		public Criteria andLicenceImgLessThanOrEqualTo(String value) {
			addCriterion("licence_img <=", value, "licenceImg");
			return (Criteria) this;
		}

		public Criteria andLicenceImgLike(String value) {
			addCriterion("licence_img like", value, "licenceImg");
			return (Criteria) this;
		}

		public Criteria andLicenceImgNotLike(String value) {
			addCriterion("licence_img not like", value, "licenceImg");
			return (Criteria) this;
		}

		public Criteria andLicenceImgIn(List<String> values) {
			addCriterion("licence_img in", values, "licenceImg");
			return (Criteria) this;
		}

		public Criteria andLicenceImgNotIn(List<String> values) {
			addCriterion("licence_img not in", values, "licenceImg");
			return (Criteria) this;
		}

		public Criteria andLicenceImgBetween(String value1, String value2) {
			addCriterion("licence_img between", value1, value2, "licenceImg");
			return (Criteria) this;
		}

		public Criteria andLicenceImgNotBetween(String value1, String value2) {
			addCriterion("licence_img not between", value1, value2, "licenceImg");
			return (Criteria) this;
		}

		public Criteria andRecommendIdIsNull() {
			addCriterion("recommend_Id is null");
			return (Criteria) this;
		}

		public Criteria andRecommendIdIsNotNull() {
			addCriterion("recommend_Id is not null");
			return (Criteria) this;
		}

		public Criteria andRecommendIdEqualTo(Integer value) {
			addCriterion("recommend_Id =", value, "recommendId");
			return (Criteria) this;
		}

		public Criteria andRecommendIdNotEqualTo(Integer value) {
			addCriterion("recommend_Id <>", value, "recommendId");
			return (Criteria) this;
		}

		public Criteria andRecommendIdGreaterThan(Integer value) {
			addCriterion("recommend_Id >", value, "recommendId");
			return (Criteria) this;
		}

		public Criteria andRecommendIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("recommend_Id >=", value, "recommendId");
			return (Criteria) this;
		}

		public Criteria andRecommendIdLessThan(Integer value) {
			addCriterion("recommend_Id <", value, "recommendId");
			return (Criteria) this;
		}

		public Criteria andRecommendIdLessThanOrEqualTo(Integer value) {
			addCriterion("recommend_Id <=", value, "recommendId");
			return (Criteria) this;
		}

		public Criteria andRecommendIdIn(List<Integer> values) {
			addCriterion("recommend_Id in", values, "recommendId");
			return (Criteria) this;
		}

		public Criteria andRecommendIdNotIn(List<Integer> values) {
			addCriterion("recommend_Id not in", values, "recommendId");
			return (Criteria) this;
		}

		public Criteria andRecommendIdBetween(Integer value1, Integer value2) {
			addCriterion("recommend_Id between", value1, value2, "recommendId");
			return (Criteria) this;
		}

		public Criteria andRecommendIdNotBetween(Integer value1, Integer value2) {
			addCriterion("recommend_Id not between", value1, value2, "recommendId");
			return (Criteria) this;
		}

		public Criteria andRemarksIsNull() {
			addCriterion("remarks is null");
			return (Criteria) this;
		}

		public Criteria andRemarksIsNotNull() {
			addCriterion("remarks is not null");
			return (Criteria) this;
		}

		public Criteria andRemarksEqualTo(String value) {
			addCriterion("remarks =", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksNotEqualTo(String value) {
			addCriterion("remarks <>", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksGreaterThan(String value) {
			addCriterion("remarks >", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksGreaterThanOrEqualTo(String value) {
			addCriterion("remarks >=", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksLessThan(String value) {
			addCriterion("remarks <", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksLessThanOrEqualTo(String value) {
			addCriterion("remarks <=", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksLike(String value) {
			addCriterion("remarks like", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksNotLike(String value) {
			addCriterion("remarks not like", value, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksIn(List<String> values) {
			addCriterion("remarks in", values, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksNotIn(List<String> values) {
			addCriterion("remarks not in", values, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksBetween(String value1, String value2) {
			addCriterion("remarks between", value1, value2, "remarks");
			return (Criteria) this;
		}

		public Criteria andRemarksNotBetween(String value1, String value2) {
			addCriterion("remarks not between", value1, value2, "remarks");
			return (Criteria) this;
		}

		public Criteria andAddTimeIsNull() {
			addCriterion("add_time is null");
			return (Criteria) this;
		}

		public Criteria andAddTimeIsNotNull() {
			addCriterion("add_time is not null");
			return (Criteria) this;
		}

		public Criteria andAddTimeEqualTo(Date value) {
			addCriterion("add_time =", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotEqualTo(Date value) {
			addCriterion("add_time <>", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeGreaterThan(Date value) {
			addCriterion("add_time >", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("add_time >=", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeLessThan(Date value) {
			addCriterion("add_time <", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeLessThanOrEqualTo(Date value) {
			addCriterion("add_time <=", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeIn(List<Date> values) {
			addCriterion("add_time in", values, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotIn(List<Date> values) {
			addCriterion("add_time not in", values, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeBetween(Date value1, Date value2) {
			addCriterion("add_time between", value1, value2, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotBetween(Date value1, Date value2) {
			addCriterion("add_time not between", value1, value2, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddAccountIsNull() {
			addCriterion("add_account is null");
			return (Criteria) this;
		}

		public Criteria andAddAccountIsNotNull() {
			addCriterion("add_account is not null");
			return (Criteria) this;
		}

		public Criteria andAddAccountEqualTo(String value) {
			addCriterion("add_account =", value, "addAccount");
			return (Criteria) this;
		}

		public Criteria andAddAccountNotEqualTo(String value) {
			addCriterion("add_account <>", value, "addAccount");
			return (Criteria) this;
		}

		public Criteria andAddAccountGreaterThan(String value) {
			addCriterion("add_account >", value, "addAccount");
			return (Criteria) this;
		}

		public Criteria andAddAccountGreaterThanOrEqualTo(String value) {
			addCriterion("add_account >=", value, "addAccount");
			return (Criteria) this;
		}

		public Criteria andAddAccountLessThan(String value) {
			addCriterion("add_account <", value, "addAccount");
			return (Criteria) this;
		}

		public Criteria andAddAccountLessThanOrEqualTo(String value) {
			addCriterion("add_account <=", value, "addAccount");
			return (Criteria) this;
		}

		public Criteria andAddAccountLike(String value) {
			addCriterion("add_account like", value, "addAccount");
			return (Criteria) this;
		}

		public Criteria andAddAccountNotLike(String value) {
			addCriterion("add_account not like", value, "addAccount");
			return (Criteria) this;
		}

		public Criteria andAddAccountIn(List<String> values) {
			addCriterion("add_account in", values, "addAccount");
			return (Criteria) this;
		}

		public Criteria andAddAccountNotIn(List<String> values) {
			addCriterion("add_account not in", values, "addAccount");
			return (Criteria) this;
		}

		public Criteria andAddAccountBetween(String value1, String value2) {
			addCriterion("add_account between", value1, value2, "addAccount");
			return (Criteria) this;
		}

		public Criteria andAddAccountNotBetween(String value1, String value2) {
			addCriterion("add_account not between", value1, value2, "addAccount");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIsNull() {
			addCriterion("modify_time is null");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIsNotNull() {
			addCriterion("modify_time is not null");
			return (Criteria) this;
		}

		public Criteria andModifyTimeEqualTo(Date value) {
			addCriterion("modify_time =", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotEqualTo(Date value) {
			addCriterion("modify_time <>", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeGreaterThan(Date value) {
			addCriterion("modify_time >", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("modify_time >=", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLessThan(Date value) {
			addCriterion("modify_time <", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
			addCriterion("modify_time <=", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIn(List<Date> values) {
			addCriterion("modify_time in", values, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotIn(List<Date> values) {
			addCriterion("modify_time not in", values, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeBetween(Date value1, Date value2) {
			addCriterion("modify_time between", value1, value2, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
			addCriterion("modify_time not between", value1, value2, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyAccountIsNull() {
			addCriterion("modify_account is null");
			return (Criteria) this;
		}

		public Criteria andModifyAccountIsNotNull() {
			addCriterion("modify_account is not null");
			return (Criteria) this;
		}

		public Criteria andModifyAccountEqualTo(String value) {
			addCriterion("modify_account =", value, "modifyAccount");
			return (Criteria) this;
		}

		public Criteria andModifyAccountNotEqualTo(String value) {
			addCriterion("modify_account <>", value, "modifyAccount");
			return (Criteria) this;
		}

		public Criteria andModifyAccountGreaterThan(String value) {
			addCriterion("modify_account >", value, "modifyAccount");
			return (Criteria) this;
		}

		public Criteria andModifyAccountGreaterThanOrEqualTo(String value) {
			addCriterion("modify_account >=", value, "modifyAccount");
			return (Criteria) this;
		}

		public Criteria andModifyAccountLessThan(String value) {
			addCriterion("modify_account <", value, "modifyAccount");
			return (Criteria) this;
		}

		public Criteria andModifyAccountLessThanOrEqualTo(String value) {
			addCriterion("modify_account <=", value, "modifyAccount");
			return (Criteria) this;
		}

		public Criteria andModifyAccountLike(String value) {
			addCriterion("modify_account like", value, "modifyAccount");
			return (Criteria) this;
		}

		public Criteria andModifyAccountNotLike(String value) {
			addCriterion("modify_account not like", value, "modifyAccount");
			return (Criteria) this;
		}

		public Criteria andModifyAccountIn(List<String> values) {
			addCriterion("modify_account in", values, "modifyAccount");
			return (Criteria) this;
		}

		public Criteria andModifyAccountNotIn(List<String> values) {
			addCriterion("modify_account not in", values, "modifyAccount");
			return (Criteria) this;
		}

		public Criteria andModifyAccountBetween(String value1, String value2) {
			addCriterion("modify_account between", value1, value2, "modifyAccount");
			return (Criteria) this;
		}

		public Criteria andModifyAccountNotBetween(String value1, String value2) {
			addCriterion("modify_account not between", value1, value2, "modifyAccount");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tenants_application
	 * @mbggenerated  Thu Apr 27 14:21:10 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tenants_application
     *
     * @mbggenerated do_not_delete_during_merge Thu Apr 06 11:49:51 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}