package com.fbee.modules.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class TenantsCustomersBase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_customers_base.CUSTOMER_ID
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_customers_base.TENANT_ID
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    private Integer tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_customers_base.CUSTOMER_MOBILE
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    private String customerMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_customers_base.CUSTOMER_NAME
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    private String customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_customers_base.SEX
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    private String sex;
    
   
    private String contactMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_customers_base.CONTACT_ADDRESS
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    private String contactAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_customers_base.AGE_RANGE
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    private String ageRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_customers_base.remarks
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_customers_base.is_usable
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    private String isUsable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_customers_base.add_time
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_customers_base.add_account
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    private String addAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_customers_base.modify_time
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_customers_base.modify_account
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    private String modifyAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_customers_base.HOUSE_TYPE
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    private String houseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_customers_base.HOUSE_AREA
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    private BigDecimal houseArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_customers_base.FAMILY_COUNT
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    private Integer familyCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_customers_base.CHILDREN_COUNT
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    private Integer childrenCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_customers_base.OLDER_COUNT
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    private Integer olderCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_customers_base.CHILDREN_AGE_RANGE
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    private String childrenAgeRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_customers_base.OLDER_AGE_RANGE
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    private String olderAgeRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_customers_base.SELF_CARES
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    private String selfCares;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_customers_base.SERVICE_PROVICE
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    private String serviceProvice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_customers_base.SERVICE_CITY
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    private String serviceCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_customers_base.SERVICE_COUNTY
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    private String serviceCounty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_customers_base.register_time
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    private Date registerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_customers_base.last_login_time
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    private Date lastLoginTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_customers_base.CUSTOMER_ID
     *
     * @return the value of tenants_customers_base.CUSTOMER_ID
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_customers_base.CUSTOMER_ID
     *
     * @param customerId the value for tenants_customers_base.CUSTOMER_ID
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_customers_base.TENANT_ID
     *
     * @return the value of tenants_customers_base.TENANT_ID
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public Integer getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_customers_base.TENANT_ID
     *
     * @param tenantId the value for tenants_customers_base.TENANT_ID
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_customers_base.CUSTOMER_MOBILE
     *
     * @return the value of tenants_customers_base.CUSTOMER_MOBILE
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public String getCustomerMobile() {
        return customerMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_customers_base.CUSTOMER_MOBILE
     *
     * @param customerMobile the value for tenants_customers_base.CUSTOMER_MOBILE
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void setCustomerMobile(String customerMobile) {
        this.customerMobile = customerMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_customers_base.CUSTOMER_NAME
     *
     * @return the value of tenants_customers_base.CUSTOMER_NAME
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_customers_base.CUSTOMER_NAME
     *
     * @param customerName the value for tenants_customers_base.CUSTOMER_NAME
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_customers_base.SEX
     *
     * @return the value of tenants_customers_base.SEX
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_customers_base.SEX
     *
     * @param sex the value for tenants_customers_base.SEX
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_customers_base.CONTACT_MOBILE
     *
     * @return the value of tenants_customers_base.CONTACT_MOBILE
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public String getContactMobile() {
        return contactMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_customers_base.CONTACT_MOBILE
     *
     * @param contactMobile the value for tenants_customers_base.CONTACT_MOBILE
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void setContactMobile(String contactMobile) {
        this.contactMobile = contactMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_customers_base.CONTACT_ADDRESS
     *
     * @return the value of tenants_customers_base.CONTACT_ADDRESS
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public String getContactAddress() {
        return contactAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_customers_base.CONTACT_ADDRESS
     *
     * @param contactAddress the value for tenants_customers_base.CONTACT_ADDRESS
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void setContactAddress(String contactAddress) {
        this.contactAddress = contactAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_customers_base.AGE_RANGE
     *
     * @return the value of tenants_customers_base.AGE_RANGE
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public String getAgeRange() {
        return ageRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_customers_base.AGE_RANGE
     *
     * @param ageRange the value for tenants_customers_base.AGE_RANGE
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void setAgeRange(String ageRange) {
        this.ageRange = ageRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_customers_base.remarks
     *
     * @return the value of tenants_customers_base.remarks
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_customers_base.remarks
     *
     * @param remarks the value for tenants_customers_base.remarks
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_customers_base.is_usable
     *
     * @return the value of tenants_customers_base.is_usable
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public String getIsUsable() {
        return isUsable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_customers_base.is_usable
     *
     * @param isUsable the value for tenants_customers_base.is_usable
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void setIsUsable(String isUsable) {
        this.isUsable = isUsable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_customers_base.add_time
     *
     * @return the value of tenants_customers_base.add_time
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_customers_base.add_time
     *
     * @param addTime the value for tenants_customers_base.add_time
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_customers_base.add_account
     *
     * @return the value of tenants_customers_base.add_account
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public String getAddAccount() {
        return addAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_customers_base.add_account
     *
     * @param addAccount the value for tenants_customers_base.add_account
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void setAddAccount(String addAccount) {
        this.addAccount = addAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_customers_base.modify_time
     *
     * @return the value of tenants_customers_base.modify_time
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_customers_base.modify_time
     *
     * @param modifyTime the value for tenants_customers_base.modify_time
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_customers_base.modify_account
     *
     * @return the value of tenants_customers_base.modify_account
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public String getModifyAccount() {
        return modifyAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_customers_base.modify_account
     *
     * @param modifyAccount the value for tenants_customers_base.modify_account
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void setModifyAccount(String modifyAccount) {
        this.modifyAccount = modifyAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_customers_base.HOUSE_TYPE
     *
     * @return the value of tenants_customers_base.HOUSE_TYPE
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public String getHouseType() {
        return houseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_customers_base.HOUSE_TYPE
     *
     * @param houseType the value for tenants_customers_base.HOUSE_TYPE
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void setHouseType(String houseType) {
        this.houseType = houseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_customers_base.HOUSE_AREA
     *
     * @return the value of tenants_customers_base.HOUSE_AREA
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public BigDecimal getHouseArea() {
        return houseArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_customers_base.HOUSE_AREA
     *
     * @param houseArea the value for tenants_customers_base.HOUSE_AREA
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void setHouseArea(BigDecimal houseArea) {
        this.houseArea = houseArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_customers_base.FAMILY_COUNT
     *
     * @return the value of tenants_customers_base.FAMILY_COUNT
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public Integer getFamilyCount() {
        return familyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_customers_base.FAMILY_COUNT
     *
     * @param familyCount the value for tenants_customers_base.FAMILY_COUNT
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void setFamilyCount(Integer familyCount) {
        this.familyCount = familyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_customers_base.CHILDREN_COUNT
     *
     * @return the value of tenants_customers_base.CHILDREN_COUNT
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public Integer getChildrenCount() {
        return childrenCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_customers_base.CHILDREN_COUNT
     *
     * @param childrenCount the value for tenants_customers_base.CHILDREN_COUNT
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void setChildrenCount(Integer childrenCount) {
        this.childrenCount = childrenCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_customers_base.OLDER_COUNT
     *
     * @return the value of tenants_customers_base.OLDER_COUNT
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public Integer getOlderCount() {
        return olderCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_customers_base.OLDER_COUNT
     *
     * @param olderCount the value for tenants_customers_base.OLDER_COUNT
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void setOlderCount(Integer olderCount) {
        this.olderCount = olderCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_customers_base.CHILDREN_AGE_RANGE
     *
     * @return the value of tenants_customers_base.CHILDREN_AGE_RANGE
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public String getChildrenAgeRange() {
        return childrenAgeRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_customers_base.CHILDREN_AGE_RANGE
     *
     * @param childrenAgeRange the value for tenants_customers_base.CHILDREN_AGE_RANGE
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void setChildrenAgeRange(String childrenAgeRange) {
        this.childrenAgeRange = childrenAgeRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_customers_base.OLDER_AGE_RANGE
     *
     * @return the value of tenants_customers_base.OLDER_AGE_RANGE
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public String getOlderAgeRange() {
        return olderAgeRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_customers_base.OLDER_AGE_RANGE
     *
     * @param olderAgeRange the value for tenants_customers_base.OLDER_AGE_RANGE
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void setOlderAgeRange(String olderAgeRange) {
        this.olderAgeRange = olderAgeRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_customers_base.SELF_CARES
     *
     * @return the value of tenants_customers_base.SELF_CARES
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public String getSelfCares() {
        return selfCares;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_customers_base.SELF_CARES
     *
     * @param selfCares the value for tenants_customers_base.SELF_CARES
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void setSelfCares(String selfCares) {
        this.selfCares = selfCares;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_customers_base.SERVICE_PROVICE
     *
     * @return the value of tenants_customers_base.SERVICE_PROVICE
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public String getServiceProvice() {
        return serviceProvice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_customers_base.SERVICE_PROVICE
     *
     * @param serviceProvice the value for tenants_customers_base.SERVICE_PROVICE
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void setServiceProvice(String serviceProvice) {
        this.serviceProvice = serviceProvice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_customers_base.SERVICE_CITY
     *
     * @return the value of tenants_customers_base.SERVICE_CITY
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public String getServiceCity() {
        return serviceCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_customers_base.SERVICE_CITY
     *
     * @param serviceCity the value for tenants_customers_base.SERVICE_CITY
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void setServiceCity(String serviceCity) {
        this.serviceCity = serviceCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_customers_base.SERVICE_COUNTY
     *
     * @return the value of tenants_customers_base.SERVICE_COUNTY
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public String getServiceCounty() {
        return serviceCounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_customers_base.SERVICE_COUNTY
     *
     * @param serviceCounty the value for tenants_customers_base.SERVICE_COUNTY
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void setServiceCounty(String serviceCounty) {
        this.serviceCounty = serviceCounty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_customers_base.register_time
     *
     * @return the value of tenants_customers_base.register_time
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_customers_base.register_time
     *
     * @param registerTime the value for tenants_customers_base.register_time
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_customers_base.last_login_time
     *
     * @return the value of tenants_customers_base.last_login_time
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_customers_base.last_login_time
     *
     * @param lastLoginTime the value for tenants_customers_base.last_login_time
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }
}