package com.fbee.modules.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class TenantsFinanceRecords {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_finance_records.IN_OUT_NO
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    private String inOutNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_finance_records.TENANT_ID
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    private Integer tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_finance_records.STAFF_ID
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    private Integer staffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_finance_records.PAY_NO
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    private String payNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_finance_records.PAY_TYPE
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    private String payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_finance_records.RELATED_TRANS
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    private String relatedTrans;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_finance_records.IN_OUT_CATEGORY
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    private String inOutCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_finance_records.IN_OUT_TYPE
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    private String inOutType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_finance_records.IN_OUT_MANTISSA
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    private String inOutMantissa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_finance_records.IN_OUT_OBJECT
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    private String inOutObject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_finance_records.IN_OUT_AMOUNT
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    private BigDecimal inOutAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_finance_records.TRANS_TYPE
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    private String transType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_finance_records.remarks
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_finance_records.add_time
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_finance_records.add_account
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    private String addAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_finance_records.modify_time
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_finance_records.modify_account
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    private String modifyAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_finance_records.is_usable
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    private String isUsable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_finance_records.status
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_finance_records.drawee_id
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    private Integer draweeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_finance_records.payee_id
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    private Integer payeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_finance_records.drawee_type
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    private String draweeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_finance_records.payee_type
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    private String payeeType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_finance_records.IN_OUT_NO
     *
     * @return the value of tenants_finance_records.IN_OUT_NO
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenants_finance_records.modify_time
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    private Date financeTime;
    
    public String getInOutNo() {
        return inOutNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_finance_records.IN_OUT_NO
     *
     * @param inOutNo the value for tenants_finance_records.IN_OUT_NO
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public void setInOutNo(String inOutNo) {
        this.inOutNo = inOutNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_finance_records.TENANT_ID
     *
     * @return the value of tenants_finance_records.TENANT_ID
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public Integer getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_finance_records.TENANT_ID
     *
     * @param tenantId the value for tenants_finance_records.TENANT_ID
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public void setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_finance_records.STAFF_ID
     *
     * @return the value of tenants_finance_records.STAFF_ID
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_finance_records.STAFF_ID
     *
     * @param staffId the value for tenants_finance_records.STAFF_ID
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_finance_records.PAY_NO
     *
     * @return the value of tenants_finance_records.PAY_NO
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public String getPayNo() {
        return payNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_finance_records.PAY_NO
     *
     * @param payNo the value for tenants_finance_records.PAY_NO
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public void setPayNo(String payNo) {
        this.payNo = payNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_finance_records.PAY_TYPE
     *
     * @return the value of tenants_finance_records.PAY_TYPE
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_finance_records.PAY_TYPE
     *
     * @param payType the value for tenants_finance_records.PAY_TYPE
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public void setPayType(String payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_finance_records.RELATED_TRANS
     *
     * @return the value of tenants_finance_records.RELATED_TRANS
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public String getRelatedTrans() {
        return relatedTrans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_finance_records.RELATED_TRANS
     *
     * @param relatedTrans the value for tenants_finance_records.RELATED_TRANS
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public void setRelatedTrans(String relatedTrans) {
        this.relatedTrans = relatedTrans;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_finance_records.IN_OUT_CATEGORY
     *
     * @return the value of tenants_finance_records.IN_OUT_CATEGORY
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public String getInOutCategory() {
        return inOutCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_finance_records.IN_OUT_CATEGORY
     *
     * @param inOutCategory the value for tenants_finance_records.IN_OUT_CATEGORY
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public void setInOutCategory(String inOutCategory) {
        this.inOutCategory = inOutCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_finance_records.IN_OUT_TYPE
     *
     * @return the value of tenants_finance_records.IN_OUT_TYPE
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public String getInOutType() {
        return inOutType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_finance_records.IN_OUT_TYPE
     *
     * @param inOutType the value for tenants_finance_records.IN_OUT_TYPE
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public void setInOutType(String inOutType) {
        this.inOutType = inOutType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_finance_records.IN_OUT_MANTISSA
     *
     * @return the value of tenants_finance_records.IN_OUT_MANTISSA
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public String getInOutMantissa() {
        return inOutMantissa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_finance_records.IN_OUT_MANTISSA
     *
     * @param inOutMantissa the value for tenants_finance_records.IN_OUT_MANTISSA
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public void setInOutMantissa(String inOutMantissa) {
        this.inOutMantissa = inOutMantissa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_finance_records.IN_OUT_OBJECT
     *
     * @return the value of tenants_finance_records.IN_OUT_OBJECT
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public String getInOutObject() {
        return inOutObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_finance_records.IN_OUT_OBJECT
     *
     * @param inOutObject the value for tenants_finance_records.IN_OUT_OBJECT
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public void setInOutObject(String inOutObject) {
        this.inOutObject = inOutObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_finance_records.IN_OUT_AMOUNT
     *
     * @return the value of tenants_finance_records.IN_OUT_AMOUNT
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public BigDecimal getInOutAmount() {
        return inOutAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_finance_records.IN_OUT_AMOUNT
     *
     * @param inOutAmount the value for tenants_finance_records.IN_OUT_AMOUNT
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public void setInOutAmount(BigDecimal inOutAmount) {
        this.inOutAmount = inOutAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_finance_records.TRANS_TYPE
     *
     * @return the value of tenants_finance_records.TRANS_TYPE
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public String getTransType() {
        return transType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_finance_records.TRANS_TYPE
     *
     * @param transType the value for tenants_finance_records.TRANS_TYPE
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public void setTransType(String transType) {
        this.transType = transType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_finance_records.remarks
     *
     * @return the value of tenants_finance_records.remarks
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_finance_records.remarks
     *
     * @param remarks the value for tenants_finance_records.remarks
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_finance_records.add_time
     *
     * @return the value of tenants_finance_records.add_time
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_finance_records.add_time
     *
     * @param addTime the value for tenants_finance_records.add_time
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_finance_records.add_account
     *
     * @return the value of tenants_finance_records.add_account
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public String getAddAccount() {
        return addAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_finance_records.add_account
     *
     * @param addAccount the value for tenants_finance_records.add_account
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public void setAddAccount(String addAccount) {
        this.addAccount = addAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_finance_records.modify_time
     *
     * @return the value of tenants_finance_records.modify_time
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_finance_records.modify_time
     *
     * @param modifyTime the value for tenants_finance_records.modify_time
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_finance_records.modify_account
     *
     * @return the value of tenants_finance_records.modify_account
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public String getModifyAccount() {
        return modifyAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_finance_records.modify_account
     *
     * @param modifyAccount the value for tenants_finance_records.modify_account
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public void setModifyAccount(String modifyAccount) {
        this.modifyAccount = modifyAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_finance_records.is_usable
     *
     * @return the value of tenants_finance_records.is_usable
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public String getIsUsable() {
        return isUsable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_finance_records.is_usable
     *
     * @param isUsable the value for tenants_finance_records.is_usable
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public void setIsUsable(String isUsable) {
        this.isUsable = isUsable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_finance_records.status
     *
     * @return the value of tenants_finance_records.status
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_finance_records.status
     *
     * @param status the value for tenants_finance_records.status
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_finance_records.drawee_id
     *
     * @return the value of tenants_finance_records.drawee_id
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public Integer getDraweeId() {
        return draweeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_finance_records.drawee_id
     *
     * @param draweeId the value for tenants_finance_records.drawee_id
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public void setDraweeId(Integer draweeId) {
        this.draweeId = draweeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_finance_records.payee_id
     *
     * @return the value of tenants_finance_records.payee_id
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public Integer getPayeeId() {
        return payeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_finance_records.payee_id
     *
     * @param payeeId the value for tenants_finance_records.payee_id
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public void setPayeeId(Integer payeeId) {
        this.payeeId = payeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_finance_records.drawee_type
     *
     * @return the value of tenants_finance_records.drawee_type
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public String getDraweeType() {
        return draweeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_finance_records.drawee_type
     *
     * @param draweeType the value for tenants_finance_records.drawee_type
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public void setDraweeType(String draweeType) {
        this.draweeType = draweeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenants_finance_records.payee_type
     *
     * @return the value of tenants_finance_records.payee_type
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public String getPayeeType() {
        return payeeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenants_finance_records.payee_type
     *
     * @param payeeType the value for tenants_finance_records.payee_type
     *
     * @mbggenerated Mon Feb 27 13:59:01 CST 2017
     */
    public void setPayeeType(String payeeType) {
        this.payeeType = payeeType;
    }

	public Date getFinanceTime() {
		return financeTime;
	}

	public void setFinanceTime(Date financeTime) {
		this.financeTime = financeTime;
	}
}