package com.fbee.modules.mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class TsysMaxNoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_max_no
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_max_no
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sys_max_no
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_max_no
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public TsysMaxNoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_max_no
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_max_no
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_max_no
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_max_no
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_max_no
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_max_no
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_max_no
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_max_no
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_max_no
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_max_no
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sys_max_no
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSysMaxNoIdIsNull() {
            addCriterion("SYS_MAX_NO_ID is null");
            return (Criteria) this;
        }

        public Criteria andSysMaxNoIdIsNotNull() {
            addCriterion("SYS_MAX_NO_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSysMaxNoIdEqualTo(Long value) {
            addCriterion("SYS_MAX_NO_ID =", value, "sysMaxNoId");
            return (Criteria) this;
        }

        public Criteria andSysMaxNoIdNotEqualTo(Long value) {
            addCriterion("SYS_MAX_NO_ID <>", value, "sysMaxNoId");
            return (Criteria) this;
        }

        public Criteria andSysMaxNoIdGreaterThan(Long value) {
            addCriterion("SYS_MAX_NO_ID >", value, "sysMaxNoId");
            return (Criteria) this;
        }

        public Criteria andSysMaxNoIdGreaterThanOrEqualTo(Long value) {
            addCriterion("SYS_MAX_NO_ID >=", value, "sysMaxNoId");
            return (Criteria) this;
        }

        public Criteria andSysMaxNoIdLessThan(Long value) {
            addCriterion("SYS_MAX_NO_ID <", value, "sysMaxNoId");
            return (Criteria) this;
        }

        public Criteria andSysMaxNoIdLessThanOrEqualTo(Long value) {
            addCriterion("SYS_MAX_NO_ID <=", value, "sysMaxNoId");
            return (Criteria) this;
        }

        public Criteria andSysMaxNoIdIn(List<Long> values) {
            addCriterion("SYS_MAX_NO_ID in", values, "sysMaxNoId");
            return (Criteria) this;
        }

        public Criteria andSysMaxNoIdNotIn(List<Long> values) {
            addCriterion("SYS_MAX_NO_ID not in", values, "sysMaxNoId");
            return (Criteria) this;
        }

        public Criteria andSysMaxNoIdBetween(Long value1, Long value2) {
            addCriterion("SYS_MAX_NO_ID between", value1, value2, "sysMaxNoId");
            return (Criteria) this;
        }

        public Criteria andSysMaxNoIdNotBetween(Long value1, Long value2) {
            addCriterion("SYS_MAX_NO_ID not between", value1, value2, "sysMaxNoId");
            return (Criteria) this;
        }

        public Criteria andMaxNoIsNull() {
            addCriterion("MAX_NO is null");
            return (Criteria) this;
        }

        public Criteria andMaxNoIsNotNull() {
            addCriterion("MAX_NO is not null");
            return (Criteria) this;
        }

        public Criteria andMaxNoEqualTo(String value) {
            addCriterion("MAX_NO =", value, "maxNo");
            return (Criteria) this;
        }

        public Criteria andMaxNoNotEqualTo(String value) {
            addCriterion("MAX_NO <>", value, "maxNo");
            return (Criteria) this;
        }

        public Criteria andMaxNoGreaterThan(String value) {
            addCriterion("MAX_NO >", value, "maxNo");
            return (Criteria) this;
        }

        public Criteria andMaxNoGreaterThanOrEqualTo(String value) {
            addCriterion("MAX_NO >=", value, "maxNo");
            return (Criteria) this;
        }

        public Criteria andMaxNoLessThan(String value) {
            addCriterion("MAX_NO <", value, "maxNo");
            return (Criteria) this;
        }

        public Criteria andMaxNoLessThanOrEqualTo(String value) {
            addCriterion("MAX_NO <=", value, "maxNo");
            return (Criteria) this;
        }

        public Criteria andMaxNoLike(String value) {
            addCriterion("MAX_NO like", value, "maxNo");
            return (Criteria) this;
        }

        public Criteria andMaxNoNotLike(String value) {
            addCriterion("MAX_NO not like", value, "maxNo");
            return (Criteria) this;
        }

        public Criteria andMaxNoIn(List<String> values) {
            addCriterion("MAX_NO in", values, "maxNo");
            return (Criteria) this;
        }

        public Criteria andMaxNoNotIn(List<String> values) {
            addCriterion("MAX_NO not in", values, "maxNo");
            return (Criteria) this;
        }

        public Criteria andMaxNoBetween(String value1, String value2) {
            addCriterion("MAX_NO between", value1, value2, "maxNo");
            return (Criteria) this;
        }

        public Criteria andMaxNoNotBetween(String value1, String value2) {
            addCriterion("MAX_NO not between", value1, value2, "maxNo");
            return (Criteria) this;
        }

        public Criteria andMaxNoTypeIsNull() {
            addCriterion("MAX_NO_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andMaxNoTypeIsNotNull() {
            addCriterion("MAX_NO_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andMaxNoTypeEqualTo(String value) {
            addCriterion("MAX_NO_TYPE =", value, "maxNoType");
            return (Criteria) this;
        }

        public Criteria andMaxNoTypeNotEqualTo(String value) {
            addCriterion("MAX_NO_TYPE <>", value, "maxNoType");
            return (Criteria) this;
        }

        public Criteria andMaxNoTypeGreaterThan(String value) {
            addCriterion("MAX_NO_TYPE >", value, "maxNoType");
            return (Criteria) this;
        }

        public Criteria andMaxNoTypeGreaterThanOrEqualTo(String value) {
            addCriterion("MAX_NO_TYPE >=", value, "maxNoType");
            return (Criteria) this;
        }

        public Criteria andMaxNoTypeLessThan(String value) {
            addCriterion("MAX_NO_TYPE <", value, "maxNoType");
            return (Criteria) this;
        }

        public Criteria andMaxNoTypeLessThanOrEqualTo(String value) {
            addCriterion("MAX_NO_TYPE <=", value, "maxNoType");
            return (Criteria) this;
        }

        public Criteria andMaxNoTypeLike(String value) {
            addCriterion("MAX_NO_TYPE like", value, "maxNoType");
            return (Criteria) this;
        }

        public Criteria andMaxNoTypeNotLike(String value) {
            addCriterion("MAX_NO_TYPE not like", value, "maxNoType");
            return (Criteria) this;
        }

        public Criteria andMaxNoTypeIn(List<String> values) {
            addCriterion("MAX_NO_TYPE in", values, "maxNoType");
            return (Criteria) this;
        }

        public Criteria andMaxNoTypeNotIn(List<String> values) {
            addCriterion("MAX_NO_TYPE not in", values, "maxNoType");
            return (Criteria) this;
        }

        public Criteria andMaxNoTypeBetween(String value1, String value2) {
            addCriterion("MAX_NO_TYPE between", value1, value2, "maxNoType");
            return (Criteria) this;
        }

        public Criteria andMaxNoTypeNotBetween(String value1, String value2) {
            addCriterion("MAX_NO_TYPE not between", value1, value2, "maxNoType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sys_max_no
     *
     * @mbggenerated do_not_delete_during_merge Fri Mar 10 15:30:19 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sys_max_no
     *
     * @mbggenerated Fri Mar 10 15:30:19 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}